library(ggplot2)
str(mpg)
qplot(displ, hwy, data = mpg)
qplot(displ, hwy, data = mpg, color=drv)
qplot(displ, hwy, data = mpg, shape = drv)
qplot(displ, hwy, data = mpg, geom = c("point", "smooth"))
qplot(displ, hwy, data = mpg) + geom_smooth()
qplot(log(displ), log(hwy), data = mpg, geom = c("point", "smooth"))
qplot(log(displ), log(hwy), data = mpg, color = drv, geom = c("point", "smooth"))
qplot(log(displ), log(hwy), data = mpg, color = drv, geom = c("point", "smooth"), method = "lm")
qplot(log(displ), log(hwy), data = mpg, facets = .~drv, geom = c("point", "smooth"), method = "lm")
qplot(hwy, data=mpg, fill = drv)
qplot(displ, data=mpg, fill = drv)
qplot(displ, hwy, data = mpg, facets = .~drv)
qplot(hwy, data = mpg, facets = drv~.)
qplot(log(displ), data = mpg, geom = "density")
qplot(hwy, data = mpg, geom = "density", color = drv)
qplot(displ, hwy, data = mpg,shape = drv)
qplot(displ, hwy, data = mpg,color = drv)
ggplot(mpg) + geom_point() + aes(displ, hwy)
ggplot(mpg) + geom_point() + aes(displ, hwy) + geom_smooth()
ggplot(mpg) + geom_point() + aes(displ, hwy) + geom_smooth(method = "lm")
ggplot(mpg) + geom_point() + aes(displ, hwy) + geom_smooth(method = "lm") + facet_grid(.~drv)
ggplot(mpg) + geom_point() + aes(displ, hwy) + geom_smooth(method = "lm") + facet_grid(drv~.)
ggplot(mpg) + aes(displ, hwy) + geom_point(aes(color = drv), size = 4, alpha = 1/2)
ggplot(mpg) + aes(displ, hwy) + geom_point(aes(color = drv), size = 4, alpha = 1/2) + geom_smooth(size = 4, linetype = 3, method = "lm", se = FALSE)
ggplot(mpg) + aes(displ, hwy) + geom_point(aes(color = drv), size = 4, alpha = 1/2) + geom_smooth(size = 4, linetype = 3, method = "lm", se = FALSE) + theme_bw(base_family="Times")

testdat<- data.frame(x=1:100, y = rnorm(100))
testdat[50,2] <- 100 ## Outlier
with(testdat, plot(x,y,type="l", ylim = c(-3,3)))
with(testdat, plot(x,y,type="l"))
g <- ggplot(testdat,aes(x=x, y=y))
g + geom_point()
g + geom_line()
g + geom_line() + ylim(-3,3) ## This will subset the data and not include the outlier.
g + geom_line() + coord_cartesian(ylim = c(-3,3))

cutpoints <- with(mpg, quantile(hwy))
mpg$hwy_q <- cut(mpg$hwy, cutpoints)
levels(mpg$hwy_q)

## Making big graph

g <- ggplot(mpg, aes(displ, cty))
g <- g + geom_point(alpha = 1/3)
g <- g + facet_wrap(year ~ hwy_q, ncol = 4)
g <- g + geom_smooth(method = "lm", se = FALSE, col = "steelblue")
g <- g + theme_bw(base_family = "Avenir", base_size = 10)
g <- g + labs(x = expression("Displacement " [displ]))
g <- g + labs(y = expression("City------------"))
g <- g + labs(title = "Comparing Displacement vs City based on each year and Mileage")

